[package]
name = "axum_newsletter"
version = "0.1.0"
authors = ["Gabriel Aguiar <gabriel.masarin.aguiar@gmail.com>"]
edition = "2021"
[lib]
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.7.4"
config = "0.14.0"
diesel = "2.1.4"
diesel-async = { version = "0.4.1", features = ["postgres"] }
reqwest = "0.11.24"
serde = { version = "1.0.196", features = ["derive"] }
tokio = { version = "1.35.1", features = ["macros", "rt-multi-thread"] }
